## 数组创建

### 从常规Python列表或元组中创建数组

使用numpy.array函数

```
numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)
```

参数名称 | 描述
:----|:----
object | 数组或嵌套的数列
dtype | 数组元素的数据类型，可选
copy | 对象是否需要复制，可选
order | 创建数组的样式，C为行方向，F为列方向，A为任意方向（默认）
subok | 默认返回一个与基类类型一致的数组
ndmin | 指定生成数组的最小维度

In [7]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
print(a)

[[1 2]
 [3 4]]


### 从数值范围创建数组。

#### numpy.arange
```
numpy.arange(start, stop, step, dtype)
```

参数名称 | 描述
:----|:----
start | 起始值，默认为0
stop | 终止值（不包含）
step | 步长，默认为1
dtype | 返回ndarray的数据类型，如果没有提供，则会使用输入数据的类型。

#### numpy.linspace

numpy.linspace 函数用于创建一个一维数组，数组是一个等差数列构成

```
np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
```

参数名称 | 描述
:----|:----
start | 序列的起始值
stop | 序列的终止值，如果endpoint为true，该值包含于数列中
num | 要生成的等步长的样本数量，默认为50
endpoint | 该值为 true 时，数列中中包含stop值，反之不包含，默认是True。
retstep | 如果为 True 时，生成的数组中会显示间距，反之不显示。
dtype | ndarray 的数据类型

#### numpy.logspace

numpy.logspace 函数用于创建一个于等比数列。

```
np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)
```

参数名称 | 描述
:----|:----
start | 序列的起始值为：base ** start
stop | 序列的终止值为：base ** stop。如果endpoint为true，该值包含于数列中
num | 要生成的等步长的样本数量，默认为50
endpoint | 该值为 true 时，数列中中包含stop值，反之不包含，默认是True。
base | 对数 log 的底数。
dtype | ndarray 的数据类型

In [8]:
import numpy as np
x = np.arange(10, 20, 2)  
print (x)


[10 12 14 16 18]


In [9]:
import numpy as np
x = np.linspace(10, 20, 5, endpoint = False)  
print (x)

[10. 12. 14. 16. 18.]


In [10]:
import numpy as np
x = np.logspace(1, 10, 10, base = 2)  
print (x)

[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]


### 使用初始占位符函数创建数组

#### numpy.empty

numpy.empty 方法用来创建一个指定形状（shape）、数据类型（dtype）且未初始化（数组元素为随机值）的数组

```
numpy.empty(shape, dtype = float, order = 'C')
```

参数名称 | 描述
:----|:----
shape | 数组形状
dtype | 数据类型，可选
order | 有"C"和"F"两个选项,分别代表，行优先和列优先，在计算机内存中的存储元素的顺序。

#### numpy.zeros

创建指定大小的数组，数组元素以 0 来填充

```
numpy.zeros(shape, dtype = float, order = 'C')
```

参数名称 | 描述
:----|:----
shape | 数组形状
dtype | 数据类型，可选
order | 有"C"和"F"两个选项,分别代表，行优先和列优先，在计算机内存中的存储元素的顺序。


#### numpy.ones

创建指定形状的数组，数组元素以 1 来填充

```
numpy.ones(shape, dtype = None, order = 'C')
```

参数名称 | 描述
:----|:----
shape | 数组形状
dtype | 数据类型，可选
order | 有"C"和"F"两个选项,分别代表，行优先和列优先，在计算机内存中的存储元素的顺序。

In [7]:
import numpy as np

a = np.empty((3, 2), dtype = int)
b = np.zeros((3, 2))
c = np.ones((3, 2))

print(a)
print('-' * 20)
print(b)
print('-' * 20)
print(c)

[[250475664       407]
 [        0         0]
 [        1   7209065]]
--------------------
[[0. 0.]
 [0. 0.]
 [0. 0.]]
--------------------
[[1. 1.]
 [1. 1.]
 [1. 1.]]
