## 数组索引、切片和迭代

数组可以进行索引、切片和迭代操作的，就像 列表 和其他Python序列类型一样。

In [4]:
import numpy as np

a = np.arange(10)

print(a)
print('\n')
print(a[2])
print('\n')
print(a[2:])
print('\n')
print(a[2:5])
print('\n')
print(a[2::2])

[0 1 2 3 4 5 6 7 8 9]


2


[2 3 4 5 6 7 8 9]


[2 3 4]


[2 4 6 8]


多维的数组每个轴可以有一个索引。这些索引以逗号分隔的元组给出：

In [7]:
import numpy as np

def f(x, y):
    return x * 10 + y

a = np.fromfunction(f,(5,4),dtype=int)

print(a)
print('\n')
print(a[2, 3])
print('\n')
print(a[0:5, 1])
print('\n')
print(a[ : ,1:3])
print('\n')
print(a[1:3, : ])


[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]


23


[ 1 11 21 31 41]


[[ 1  2]
 [11 12]
 [21 22]
 [31 32]
 [41 42]]


[[10 11 12 13]
 [20 21 22 23]]


切片还可以包括省略号 …，来使选择元组的长度与数组的维度相同。

In [9]:
import numpy as np
 
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print (a)
print('\n')
print (a[...,1])
print('\n')
print (a[1,...])
print('\n')
print (a[...,1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]


[2 4 5]


[3 4 5]


[[2 3]
 [4 5]
 [5 6]]


对多维数组进行 迭代（Iterating） 是相对于第一个轴完成的：

In [12]:
import numpy as np
 
a = np.array([[1,2,3],[3,4,5],[4,5,6]])

print(a)
print('\n')

for row in a:
    print(row)

[[1 2 3]
 [3 4 5]
 [4 5 6]]


[1 2 3]
[3 4 5]
[4 5 6]


如果想要对数组中的每个元素执行操作，可以使用flat属性

In [14]:
import numpy as np
 
a = np.array([[1,2,3],[3,4,5],[4,5,6]])

print(a)
print('\n')

for element in a.flat:
    print(element)

[[1 2 3]
 [3 4 5]
 [4 5 6]]


1
2
3
3
4
5
4
5
6


## 花式索引和索引技巧

NumPy提供比常规Python序列更多的索引功能。除了通过整数和切片进行索引之外，数组还可以由整数数组和布尔数组索引。

### 使用索引数组进行索引

In [17]:
import numpy as np
 
a = np.arange(12)**2

print(a)
print('\n')

i = np.array( [ 1,1,3,8,5 ] )
# the elements of a at the positions i
print(a[i])

j = np.array( [ [ 3, 4], [ 9, 7 ] ] )
# the same shape as j
print(a[j])

[  0   1   4   9  16  25  36  49  64  81 100 121]


[ 1  1  9 64 25]
[[ 9 16]
 [81 49]]


### 使用布尔数组进行索引

In [19]:
import numpy as np
 
a = np.arange(12).reshape(3,4)

print(a)
print('\n')

b = a > 4
print(b)
print('\n')

print(a[b])
print('\n')

a[b] = 0
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


[ 5  6  7  8  9 10 11]


[[0 1 2 3]
 [4 0 0 0]
 [0 0 0 0]]


### ix_()函数

ix_ 函数可用于组合不同的向量，以便获得每个n-uplet的结果。

例如，如果要计算从每个向量a，b和c中取得的所有三元组的所有a + b * c：

In [22]:
import numpy as np

a = np.array([2,3,4,5])
b = np.array([8,5,4])
c = np.array([5,4,6,8,3])

ax,bx,cx = np.ix_(a,b,c)

print(ax)
print('\n')
print(bx)
print('\n')
print(cx)
print('\n')

print(ax.shape, bx.shape, cx.shape)
print('\n')

result = ax+bx*cx
print(result)
print('\n')
print(result.shape)

[[[2]]

 [[3]]

 [[4]]

 [[5]]]


[[[8]
  [5]
  [4]]]


[[[5 4 6 8 3]]]


(4, 1, 1) (1, 3, 1) (1, 1, 5)


[[[42 34 50 66 26]
  [27 22 32 42 17]
  [22 18 26 34 14]]

 [[43 35 51 67 27]
  [28 23 33 43 18]
  [23 19 27 35 15]]

 [[44 36 52 68 28]
  [29 24 34 44 19]
  [24 20 28 36 16]]

 [[45 37 53 69 29]
  [30 25 35 45 20]
  [25 21 29 37 17]]]


(4, 3, 5)
