## 数组元素操作

### Agenda

- 数组基本运算
- 统计函数
- 其他通函数

### 数组基本运算
数组上的算术运算符会应用到 元素 级别。

In [1]:
import numpy as np

a = np.array( [20,30,40,50] )
b = np.arange( 4 )

print(a-b)
print('\n')

print(b**2)
print('\n')

print(10*np.sin(a))
print('\n')

print(a < 35)

[20 29 38 47]


[0 1 4 9]


[ 9.12945251 -9.88031624  7.4511316  -2.62374854]


[ True  True False False]


与许多矩阵语言不同，乘积运算符*在NumPy数组中按元素进行运算。矩阵乘积可以使用@运算符（在python> = 3.5中）或dot函数或方法执行：

In [2]:
import numpy as np

a = np.array( [[1,1],
                [0,1]] )
b = np.array( [[2,0],
                [3,4]] )

print(a*b)
print('\n')

print(a@b)
print('\n')

print(a.dot(b))

[[2 0]
 [0 4]]


[[5 4]
 [3 4]]


[[5 4]
 [3 4]]


### 统计函数
许多一元操作，例如计算数组中所有元素的总和，都是作为ndarray类的方法实现的。

In [10]:
import numpy as np

a = np.random.random((2,3))

print(a)
print('\n')

print(a.max())
print('\n')

print(a.min())
print('\n')

print(a.sum())
print('\n')

print(a.cumsum())

[[0.02056687 0.50507356 0.33728773]
 [0.78762821 0.97758817 0.70379367]]


0.9775881655000612


0.02056687297536064


3.3319382096333285


[0.02056687 0.52564043 0.86292817 1.65055637 2.62814454 3.33193821]


通过指定axis 参数，您可以沿数组的指定轴应用操作：

In [9]:
b = np.arange(12).reshape(3,4)

print(b)
print('\n')

print(b.max(axis=1))
print('\n')

print(b.min(axis=1))
print('\n')

print(b.sum(axis=1))
print('\n')

print(b.cumsum(axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[ 3  7 11]


[0 4 8]


[ 6 22 38]


[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]
[ 0  1  3  6 10 15 21 28 36 45 55 66]


## 其他通函数

NumPy提供熟悉的数学函数，例如sin，cos和exp。在NumPy中，这些被称为“通函数”（ufunc）。在NumPy中，这些函数在数组上按元素进行运算，产生一个数组作为输出。

* **数学**
* **算术**
* **统计**
* **询问**
* **排序**