## 数组操作

### 修改数组形状

函数 | 描述
:----|:----
reshape | 不改变数据的条件下修改形状
ravel | 返回展开数组
resize | 修改数组本身

In [5]:
import numpy as np
 
a = np.arange(8)
print ('原始数组：')
print (a)
print ('\n')
 
b = a.reshape(4,2)
print ('修改后的数组1：')
print (b)
print ('\n')

#如果在 reshape 操作中将 size 指定为-1，则会自动计算其他的 size 大小
b = a.reshape(2,-1)
print ('修改后的数组2：')
print (b)

原始数组：
[0 1 2 3 4 5 6 7]


修改后的数组：
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


修改后的数组：
[[0 1 2 3]
 [4 5 6 7]]


In [4]:
import numpy as np
 
a = np.arange(8).reshape(2,4)
 
print ('原数组：')
print (a)
print ('\n')
 
print ('调用 ravel 函数之后：')
print (a.ravel())
print ('\n')
 
print ('以 FORTRAN 风格顺序调用 ravel 函数之后：')
print (a.ravel(order = 'F'))

原数组：
[[0 1 2 3]
 [4 5 6 7]]


调用 ravel 函数之后：
[0 1 2 3 4 5 6 7]


以 F 风格顺序调用 ravel 函数之后：
[0 4 1 5 2 6 3 7]
原数组：
[[0 1 2 3]
 [4 5 6 7]]




In [10]:
import numpy as np
 
a = np.arange(8).reshape(2, 4)
 
print ('原数组：')
print (a)
print ('\n')
 

a.resize(4, 2)
print ('调用 resize 函数之后：')
print (a)
print ('\n')

原数组：
[[0 1 2 3]
 [4 5 6 7]]


调用 resize 函数之后：
[[0 1]
 [2 3]
 [4 5]
 [6 7]]




### 翻转数组

函数 | 描述
:----|:----
ndarray.T | 对换数组的维度
rollaxis | 向后滚动指定的轴
swapaxes | 对换数组的两个轴

In [14]:
import numpy as np
 
a = np.arange(12).reshape(3,4)
 
print ('原数组：')
print (a)
print (a.shape)
print ('\n')
 
print ('转置数组：')
print (a.T)
print (a.T.shape)

原数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


转置数组：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
(4, 3)


In [16]:
import numpy as np
 
# 创建了三维的 ndarray
a = np.arange(12).reshape(3,2,2)
 
print ('原数组：')
print (a)
print ('\n')
# 现在交换轴 0（深度方向）到轴 2（宽度方向）
 
print ('调用 swapaxes 函数后的数组：')
print (np.swapaxes(a, 2, 0))


原数组：
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


调用 swapaxes 函数后的数组：
[[[ 0  4  8]
  [ 2  6 10]]

 [[ 1  5  9]
  [ 3  7 11]]]


### 修改数组维度

函数 | 描述
:----|:----
broadcast_to | 将数组广播到新形状
expand_dims | 扩展数组的形状
squeeze | 从数组的形状中删除一维条目

* **numpy.broadcast_to**

    numpy.broadcast_to 函数将数组广播到新形状。它在原始数组上返回只读视图。 它通常不连续。 如果新形状不符合 NumPy 的广播规则，该函数可能会抛出ValueError。
    ```
    numpy.broadcast_to(array, shape, subok)
    ```
    
* **numpy.expand_dims**

    umpy.expand_dims 函数通过在指定位置插入新的轴来扩展数组形状。
    ```
    numpy.expand_dims(arr, axis)
    ```
    
* **numpy.squeeze**

    numpy.squeeze 函数从给定数组的形状中删除一维的条目。
    ```
    numpy.squeeze(arr, axis)
    ```

In [15]:
import numpy as np

a = np.array([1, 2, 3, 4])  

b = np.broadcast_to(a, (2, 4))

print(b)

[[1 2 3 4]
 [1 2 3 4]]


In [18]:
import numpy as np

a = np.array([1, 2, 3, 4]) 
print(a)

y = np.expand_dims(a, 0)
print(y)

print (x.shape, y.shape)
print (x.ndim,y.ndim)

[1 2 3 4]
[[1 2 3 4]]
(1,) (1, 4)
1 2


In [21]:
import numpy as np

a = np.arange(9).reshape(1,3,3)
print(a)

b = np.squeeze(a)
print(b)

[[[0 1 2]
  [3 4 5]
  [6 7 8]]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 连接数组

函数 | 描述
:----|:----
concatenate | 连接沿现有轴的数组序列
stack | 沿着新的轴加入一系列数组
hstack | 水平堆叠序列中的数组（列方向）
vstack | 竖直堆叠序列中的数组（行方向）

* **numpy.concatenate**

    numpy.concatenate 函数用于沿指定轴连接相同形状的两个或多个数组。
    ```
    numpy.concatenate((a1, a2, ...), axis)
    ```
    
* **numpy.stack**

    numpy.stack 函数用于沿新轴连接数组序列。
    ```
    numpy.stack(arrays, axis)

In [31]:
import numpy as np
 
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
 
print (a)
print ('\n')
print (b)
print ('\n')

print (np.concatenate((a,b)))
print (np.concatenate((a,b),axis = 1))

[[1 2]
 [3 4]]


[[5 6]
 [7 8]]


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [32]:
import numpy as np

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print (a)
print ('\n')
print (b)
print ('\n')

print (np.stack((a,b)))
print ('\n')
print (np.stack((a,b), 1))
print ('\n')

print (np.hstack((a,b)))
print ('\n')
print (np.vstack((a,b)))

[[1 2]
 [3 4]]


[[5 6]
 [7 8]]


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


[[1 2 5 6]
 [3 4 7 8]]


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### 分割数组

函数 | 描述
:----|:----
split | 将一个数组分割为多个子数组
hsplit | 将一个数组水平分割为多个子数组（按列）
vsplit | 将一个数组垂直分割为多个子数组（按行）

* **numpy.split**

    numpy.split 函数沿特定的轴将数组分割为子数组。
    ```
    numpy.split(ary, indices_or_sections, axis)
    ```
    
* **numpy.hsplit**

    numpy.hsplit 函数用于水平分割数组，通过指定要返回的相同形状的数组数量来拆分原数组。
    
    
* **numpy.vsplit**

    numpy.vsplit 沿着垂直轴分割数组，通过指定要返回的相同形状的数组数量来拆分原数组。

In [34]:
import numpy as np
 
a = np.arange(9)
 
print (a)
print ('\n')
 
b = np.split(a,3)
print (b)
print ('\n')

c = np.split(a,[4,6,7])
print (c)

[0 1 2 3 4 5 6 7 8]


[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
[array([0, 1, 2, 3]), array([4, 5]), array([6]), array([7, 8])]


In [42]:
import numpy as np
 
a = np.floor(10 * np.random.random((4, 6)))
print(a)
print ('\n')
 
print(np.hsplit(a, 3))
print ('\n')

print(np.vsplit(a, 2))
print ('\n')

[[6. 6. 1. 3. 2. 9.]
 [3. 6. 0. 9. 3. 4.]
 [6. 0. 4. 2. 4. 9.]
 [7. 0. 3. 9. 9. 7.]]


[array([[6., 6.],
       [3., 6.],
       [6., 0.],
       [7., 0.]]), array([[1., 3.],
       [0., 9.],
       [4., 2.],
       [3., 9.]]), array([[2., 9.],
       [3., 4.],
       [4., 9.],
       [9., 7.]])]


[array([[6., 6., 1., 3., 2., 9.],
       [3., 6., 0., 9., 3., 4.]]), array([[6., 0., 4., 2., 4., 9.],
       [7., 0., 3., 9., 9., 7.]])]




### 数组元素的添加与删除

函数 | 描述
:----|:----
append | 将值添加到数组末尾
insert | 沿指定轴将值插入到指定下标之前
delete | 删掉某个轴的子数组，并返回删除后的新数组
unique | 去除数组中的重复元素

* **numpy.append**

    numpy.append 函数在数组的末尾添加值。
    ```
    numpy.append(arr, values, axis=None)
    ```
    
    > axis：默认为 None。当axis无定义时，是横向加成，返回总是为一维数组。
    
* **numpy.insert**

    numpy.insert 函数在给定索引之前，沿给定轴在输入数组中插入值。
    ```
    numpy.insert(arr, obj, values, axis)
    ```
    
    > 未传递 Axis 参数。 在插入之前输入数组会被展开。
    
* **numpy.delete**

    numpy.delete 函数返回从输入数组中删除指定子数组的新数组。
    ```
    numpy.delete(arr, obj, axis)
    ```
    
* **numpy.unique**

    numpy.unique 函数用于去除数组中的重复元素。
    ```
    numpy.unique(arr, return_index, return_inverse, return_counts)
    ```

In [44]:
import numpy as np
 
a = np.array([[1,2,3],[4,5,6]])
 
print (a)
print ('\n')

print (np.append(a, [7,8,9]))
print ('\n')
 
print (np.append(a, [[7,8,9]],axis = 0))
print ('\n')
 
print (np.append(a, [[3,2,1],[6,5,4]],axis = 1))


[[1 2 3]
 [4 5 6]]


[1 2 3 4 5 6 7 8 9]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[1 2 3 3 2 1]
 [4 5 6 6 5 4]]


In [46]:
import numpy as np
 
a = np.array([[1,2],[3,4],[5,6]])
 
print (a)
print ('\n')

print (np.insert(a,3,[11,12]))
print ('\n')
 
print (np.insert(a,1,11,axis = 0))
print ('\n')
 
print (np.insert(a,1,11,axis = 1))


[[1 2]
 [3 4]
 [5 6]]


[ 1  2  3 11 12  4  5  6]


[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]


[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]


In [47]:
import numpy as np
 
a = np.array([[1,2],[3,4],[5,6]])
 
print (a)
print ('\n')

print (np.delete(a,3))
print ('\n')
 
print (np.delete(a,1,axis = 0))
print ('\n')
 
print (np.delete(a,1,axis = 1))

[[1 2]
 [3 4]
 [5 6]]


[1 2 3 5 6]


[[1 2]
 [5 6]]


[[1]
 [3]
 [5]]


In [51]:
import numpy as np
 
a = np.array([1,1,2,3,4,5,5,5,6,7])

print (a)
print ('\n')

u = np.unique(a)
print (u)
print ('\n')

u,indices = np.unique(a, return_index = True)
print (indices)
print ('\n')

u,indices = np.unique(a, return_inverse = True)
print (indices)
print ('\n')

u,indices = np.unique(a,return_counts = True)
print (indices)
print ('\n')

[1 1 2 3 4 5 5 5 6 7]


[1 2 3 4 5 6 7]


[0 2 3 4 5 8 9]


[0 0 1 2 3 4 4 4 5 6]


[2 1 1 1 3 1 1]


