## 数组拷贝和视图

当计算和操作数组时，数据会不会被复制到新的数组，包括三种情况。

### Agenda

- 完全不复制
- 视图或浅拷贝
- 深拷贝

### 完全不复制

简单分配不会复制数组对象或其数据。

In [2]:
import numpy as np

a = np.arange(12)
b = a
b is a

True

### 视图或浅拷贝

不同的数组对象可以共享相同的数据。该view方法创建一个查看相同数据的新数组对象。

In [13]:
a = np.arange(12)
c = a.view()
print(a)
print(c)
print(c is a)
print(c.base is a)

print("修改a数组形状为3，4后：")
a.shape = (3,4)
print(a)
print(c)

print("修改a数组元素数据后：")
a[0,0] = 666
print(a)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
False
True
修改a数组形状为3，4后：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
修改a数组元素数据后：
[[666   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]
[666   1   2   3   4   5   6   7   8   9  10  11]


切片数组会返回一个视图：

In [16]:
a = np.arange(12).reshape(3,4)
print(a)

s = a[ : , 1:3]
print(s)

print("修改s数组元素数据后：")
s[ : ] = 10
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
修改s数组元素数据后：
[[ 0 10 10  3]
 [ 4 10 10  7]
 [ 8 10 10 11]]


### 深拷贝

copy方法生成数组及其数据的完整副本。

In [19]:
a = np.arange(12)
d = a.copy()
print(a)
print(d)
print(d is a)
print(d.base is a)

print("修改a数组元素数据后：")
a[0] = 666
print(a)
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
False
False
修改a数组元素数据后：
[666   1   2   3   4   5   6   7   8   9  10  11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
